### PR TITLE
FMSI help messages improvements and more robust argument parsing

### PR DESCRIPTION
**Pull request by OndrejSladky**
- `fmsi -h` includes help and contact.
- improved help for all subcommands
- FMSI fails if multiple `-p` provided.
- FMSI fails if `-s` not given and klcp does not exists
- FMSI does not store empty klcp array if it is not computed

### CODE REVIEW

**Comment by karel-brinda** [comment]
`fmsi clean` je pomerne nestandardni, jestli to jenom maze soubory, tak bych to tam nedaval (nebo bych to tam nechal v kodu tise, bez zminky)

**Comment by karel-brinda** [comment]
Pro `fmsi query` a `fmsi index` bych ocekaval neco v tomhle stylu:
```
Usage:   bwa index [options] <in.fasta>

Options: -a STR    BWT construction algorithm: bwtsw, is or rb2 [auto]
         -p STR    prefix of the index [same as fasta name]
         -b INT    block size for the bwtsw algorithm (effective with -a bwtsw) [10000000]
         -6        index files named as <in.fasta>.64.* instead of <in.fasta>.* 

Warning: `-a bwtsw' does not work for short genomes, while `-a is' and
         `-a div' do not work not for long genomes.


```

**Comment by karel-brinda** [comment]
Jeste poznamka – v 0.3 bychom nemeli menit parametry - jenom parsovani. Vedle toho muze byt vetev napr. devel pro 0.4, kde to muzeme vyladit (spolu s formatem indexu - k tomu mam take nejake  drobne poznamky :)).

**Comment by karel-brinda** [comment]
```
./fmsi export
>exported f-masked superstring
libc++abi: terminating due to uncaught exception of type std::length_error: vector
Abort trap: 6

```

**Comment by karel-brinda** [comment]
It's definitely much better now.

The main limitation currently is the lines are too long.

What about:
- removing the ` characters
- "The path to the masked superstring file from which the index was created. Required." -> "Index prefix (masked superstring file). Required." etc.

**Comment by OndrejSladky** [comment]
> Index prefix (masked superstring file) [required]

Shortened the cli help. LMK if there's anything else.

**Pull request merged**
